version: '3.8'

services:
  frontend-gestion:
    image: artistehmz/pharmaco-gestion:64
    container_name: frontend-gestion
    ports:
      - "5173:80"
    depends_on:
      - backend

  frontend-shop:
    image: artistehmz/pharmaco-shop:64
    container_name: frontend-shop
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: artistehmz/pharmaco-backend:64
    container_name: backend
    ports:
      - "8086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/pharmaco
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
